language: ruby
rvm:
- 2.6.3
bundler_args: --jobs 1 --retry 3
dist: trusty
sudo: required
script:
  - cp config/database.yml.sample config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/application.yml.sample config/application.yml
  - bundle exec rake db:setup
  - bundle exec rspec
cache: bundler
before_install:
  - gem install -v 1.17.2 bundler
services:
  - postgresql
addons:
  postgresql: "9.5"
after_success:
  - bundle exec codeclimate-test-reporter
