- tenure: 0.5 
  annual_leave_days: 3
- tenure: 1 
  annual_leave_days: 7
- tenure: 2 
  annual_leave_days: 10  
- tenure: 3 
  annual_leave_days: 14  
- tenure: 4 
  annual_leave_days: 14  
- tenure: 5 
  annual_leave_days: 15  
- tenure: 6 
  annual_leave_days: 15  
- tenure: 7 
  annual_leave_days: 15  
- tenure: 8 
  annual_leave_days: 15  
- tenure: 9 
  annual_leave_days: 15  
- tenure: 10
  annual_leave_days: 16
- tenure: 11
  annual_leave_days: 17
- tenure: 12
  annual_leave_days: 18
- tenure: 13
  annual_leave_days: 19
- tenure: 14
  annual_leave_days: 20
- tenure: 15
  annual_leave_days: 21
- tenure: 16
  annual_leave_days: 22
- tenure: 17
  annual_leave_days: 23
- tenure: 18
  annual_leave_days: 24
- tenure: 19
  annual_leave_days: 25
- tenure: 20
  annual_leave_days: 26
- tenure: 21
  annual_leave_days: 27
- tenure: 22
  annual_leave_days: 28
- tenure: 23
  annual_leave_days: 29
- tenure: 24
  annual_leave_days: 30
